defaults:
  - constraint_store: re_independent
  - _self_

generator_type: python
generator_mode: batch
num_processes: 12
max_retries_per_attempt: 2
output_folder: llm_string/constraint_generator/evaluations/results/
model_names:
  - gpt-4o-mini
  - gpt-4o
  - deepseek-chat
  - Meta-Llama-3.1-8B-Instruct-Turbo-128K